In [2]:
import numpy as np
import pandas as pd
data = pd.read_csv('drive/MyDrive/president_heights.csv')
heights = np.array(data['height(cm)'])

print("Mean height:        ", np.mean(heights))
print("Standard deviation: ", np.std(heights))
print("Maximum height:     ", np.max(heights))
print("Minimum height:     ", np.min(heights))
print("25th percentile:    ", np.percentile(heights, 25))
print("75th percentile:    ", np.percentile(heights, 75))
print("Median:             ", np.median(heights))

Mean height:         179.73809523809524
Standard deviation:  6.931843442745892
Maximum height:      193
Minimum height:      163
25th percentile:     174.25
75th percentile:     183.0
Median:              182.0


In [3]:
data = np.genfromtxt("drive/MyDrive/Zadanie_2.csv", delimiter = ";")
print(data)

print("Inverse matrix:\n", np.linalg.inv(data))

val,vec = np.linalg.eig(data)
print("Eigenvalues:\n", val)
print("Eigenvectors:\n", vec)

[[  1.   2.  15. -59.   9.   3.  75.   6.   7.   1.]
 [  0.   5.   0.   4.   6.  16.  44.   7.   1.   1.]
 [  7.  14.   3. -10.   9.  15.  73.   8.   2.   9.]
 [  1.   5.  15. -54.   5.  15.  35.   8.   6.   4.]
 [  0.   8.   5. -18.   7.  16.  91.   6.   7.   9.]
 [  7.  18.  23. -90.   4.   8.  31.   0.   1.   7.]
 [  2.   8.  20. -72.   4.   1.  91.   9.   4.   4.]
 [  4.  12.  18. -65.   6.   9.  76.   4.   9.   9.]
 [  7.  15.  13. -52.   5.   7.  54.   2.   7.   0.]
 [  2.   9.  15. -56.   6.   1.  98.   4.   8.   4.]]
Inverse matrix:
 [[ 0.47461371  0.13269253 -0.24726695 -0.82965177  0.28250384 -0.17012825
   0.58274426  0.83686705  0.4146721  -1.56942847]
 [-0.38032531 -0.11226789  0.23216372  0.58853747 -0.2508954   0.10174485
  -0.40729564 -0.58325689 -0.2335154   1.11832726]
 [ 0.13559662  0.58950334 -0.24709855 -0.58789838 -0.30170699 -0.12721938
   0.23740295  1.01003036 -0.02151387 -0.64590149]
 [ 0.01425207  0.14570726 -0.04557569 -0.12721972 -0.08945184 -0.03756624
   

In [6]:
rainfall = pd.read_csv('drive/MyDrive/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  # 1/10mm -> inches
inches.shape

rainy = np.count_nonzero(inches)
print("Rainy days:     ", rainy)
print("Non rainy days: ", inches.size - rainy)
print("Days above 0.5 inch of rain: ", np.count_nonzero(inches > 0.5))
print("Days below 0.2 inch of rain: ", np.count_nonzero(inches < 0.2))

Rainy days:      150
Non rainy days:  215
Days above 0.5 inch of rain:  37
Days below 0.2 inch of rain:  290


In [28]:
masked_rainy = np.ma.array(inches, mask=(inches <= 0))
print("Median precip on rainy days in 2014 (inches):   ", np.ma.median(masked_rainy)) 

masked_summer = np.ma.array(inches, mask = False)
m1 = (inches == 0)
m2 = np.ma.make_mask_none(m1.shape)
m2.fill(True)
m2[172:262] = False
masked_summer.mask = np.ma.mask_or(m1,m2)
print("Median precip on summer days in 2014 (inches):  ", np.ma.median(masked_summer))
print("Maximum precip on summer days in 2014 (inches): ", np.ma.max(masked_summer)) 

masked_no_summer = np.ma.array(masked_rainy, copy=True)
masked_no_summer.mask[172:262] = True
print("Median precip on non-summer rainy days (inches):", np.ma.median(masked_no_summer)) 

Median precip on rainy days in 2014 (inches):    0.19488188976377951
Median precip on summer days in 2014 (inches):   0.0610236220472441
Maximum precip on summer days in 2014 (inches):  0.8503937007874016
Median precip on non-summer rainy days (inches): 0.20078740157480315


In [38]:
a = [0,3,2,5]
b = [0,3,1,4]

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,4))
print(np.linalg.norm(b))

[0 6 3 9]
[0 0 1 1]
[ 0 12  8 20]
5.0990195135927845
